### PR TITLE
Fix callbacks return values

### PR DESCRIPTION
**Pull request by azhuk-softheme**
Return real return value instead of 0 in case of void

### CODE REVIEW

**Comment by ensirius** [comment]
Looks like your commit not bind to your username

**Comment by SerCeMan** [comment]
Thank you very much! This is a very important issue.

**Comment by SerCeMan** [comment]
Hi!

I've just pushed a release `0.3.1` with your fix. Please check that everything works well.

Thank you again for this important fix!

**Comment by azhuk-softheme** [comment]
@ensirius my bad, it appears i used email, which differs from account one

@SerCeMan thanks for release, that worked for me

**Pull request merged**
