### PR TITLE
FuseStubFS.getContext()

### PR DESCRIPTION
**Pull request by mlhartme**
I needed access to fuse_context, so I've added this code. If you think it's generally useful, please pull it :)

(I'm new to jnr, there might be better ways to implement this ...)

### CODE REVIEW

**Comment by SerCeMan** [comment]
Hi, @mlhartme!

Thank you for the contribution! Changes looks good to me :) 

Am I right that the comment in your last commit can be removed?

**Comment by mlhartme** [comment]
Correct. And I've added more struct fields.

**Comment by SerCeMan** [comment]
@mlhartme Nice 🎉  Thanks for that

**Comment by pafgoncalves** [comment]
Can you make a release with this PR?
I need this functionality and it would be nice to have a maven release (maybe 0.4.1).

Thanks

**Comment by SerCeMan** [comment]
Hi, @pafgoncalves!

Yes, it makes sense to publish a release with the PR included. 
Done, you can check out `0.4.1` version.

**Pull request merged**
